### ISSUE TITLE
Provision and deploy database to hold latest dataset

### ISSUE THREAD

**Issue by charlienewey** [soton-data-mining/job-salary-prediction#15]
Create "production" instance of MongoDB to hold latest version of data. This is useful while we're part-way through the data cleaning stage.

**Comment by arahayrabedian** [comment]
Created a database on an already existent mongodb setup on the university provided VM's, address and common password and username already made available to members.

Overview: 
1. mongodb container running in docker, set to restart whenever terminated (the VMs are restarted ~weekly for kernel updates)
2. set up a user with readWrite access to a specific db
3. full mongodump every 3 hours copied to soton filestore (under my user) via cronjob and small script

not sure script is relevant enough to put in to repo, but here it is for open-ness:

/media/filestore... is a samba mounted filesystem on the soton filestore - it will outlive this VM if anything happens to it.

```
#!/bin/bash

filename="mongo_dump_`date +%Y%m%d_%H%M%S`"
echo "$filename"
mongodump --username=user_with_backup_role --password=password_here --host=localhost --gzip
mv dump /media/filestore/mydocuments/backups/mongodb_backups/"$filename"
```

**Comment by arahayrabedian** [comment]
incidentally, can confirm these backups work... but at 130 mb a pop i should totally check what our quota limits are.

**Comment by arahayrabedian** [comment]
>Your default quota for your personal storage is 50GB.

should be fine for a while.
