### ISSUE TITLE
Cleaning: Extract salary range

### ISSUE THREAD

**Issue by blanche** [soton-data-mining/job-salary-prediction#2]

**Comment by utkuozbulak** [comment]
Whats that ? Can you be more explicit ?

**Comment by blanche** [comment]
extract the number from the salary range and normalize them per annum
i.e convert 
18000 - 26000/annum TO 26K BASIC + COMM + BENS
to {18000,26000}

**Comment by utkuozbulak** [comment]
Can you store min max as separate features/columns ?
