### ISSUE TITLE
Extract pixel-based feature vectors

### ISSUE THREAD

**Issue by arahayrabedian** [soton-data-mining/job-salary-prediction#28]
Use image pixels to extract elements around the eyes/nose/mouth and place in to a concatenated vector to use to feed to a learning machine.

Work with raw and normalized images.

**Comment by utkuozbulak** [comment]
Except this should be in Advanced Machine Learning, right ? :laughing:

**Comment by arahayrabedian** [comment]
yes... yes it would

**Comment by charlienewey** [comment]
![https://media.giphy.com/media/lgn6HaiiwHBXW/giphy.gif][You fool]
