### ISSUE TITLE
Distribute pre-processed/cleaned data

### ISSUE THREAD

**Issue by charlienewey** [soton-data-mining/job-salary-prediction#29]
Now that we're at the model-building stage and the data cleaning/feature engineering work is starting to slow down a bit, it would be great if we could share the new dataset on EdShare or something. That would allow us to actually get started building models.

**Comment by utkuozbulak** [comment]
Hey, do we need to distribute the data? You will only need to run/clean the data once and once only when you run the BaseMethod, see #36

**Comment by utkuozbulak** [comment]
Done with #36
