### ISSUE TITLE
Cleaning: +Salary Benefits

### ISSUE THREAD

**Issue by utkuozbulak** [soton-data-mining/job-salary-prediction#8]
Separate possible additions to salary and (maybe) store them as a different feature. E.g:

$$$ + Tips 
$$$ + Benefits
$$$ + Bonus
^ Those things will increase the normalized salary and its smarter to keep as a separate feature.

We can even come up with more than one benefits features in one hot encoded form:
Tips | Benefits | Bonus | Package ...
1,1,0,0...
0,0,0,0...
1,0,0,0...
0,0,0,1...

**Comment by blanche** [comment]
I wonder if it's worth doing the same for hourly / annually and see if there is a pattern and we can say "this job will most likely be payed annually/hourly"
